module Tracks exposing (..)

import Model exposing (..)


tracks3by3 =
    [ [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
    , [ Empty, Empty, Empty, Empty, DownRight, DownLeft, Empty, UpRight, UpLeft ]
    , [ Empty, Empty, Empty, DownRight, Horizontal, DownLeft, UpRight, Horizontal, UpLeft ]
    , [ Empty, Empty, Empty, DownRight, DownLeft, Empty, UpRight, UpLeft, Empty ]
    , [ Empty, DownRight, DownLeft, Empty, Vertical, Vertical, Empty, UpRight, UpLeft ]
    , [ Empty, DownRight, DownLeft, Empty, UpRight, UpLeft, Empty, Empty, Empty ]
    , [ Empty, DownRight, DownLeft, DownRight, UpLeft, Vertical, UpRight, Horizontal, UpLeft ]
    , [ Empty, DownRight, DownLeft, DownRight, Cross, UpLeft, UpRight, UpLeft, Empty ]
    , [ DownRight, Horizontal, DownLeft, Vertical, Empty, Vertical, UpRight, Horizontal, UpLeft ]
    , [ DownRight, Horizontal, DownLeft, Vertical, DownRight, UpLeft, UpRight, UpLeft, Empty ]
    , [ DownRight, Horizontal, DownLeft, UpRight, Horizontal, UpLeft, Empty, Empty, Empty ]
    , [ DownRight, Horizontal, DownLeft, UpRight, DownLeft, Vertical, Empty, UpRight, UpLeft ]
    , [ DownRight, DownLeft, Empty, Vertical, Vertical, Empty, UpRight, UpLeft, Empty ]
    , [ DownRight, DownLeft, Empty, Vertical, UpRight, DownLeft, UpRight, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, Empty, UpRight, UpLeft, Empty, Empty, Empty, Empty ]
    , [ DownRight, DownLeft, Empty, UpRight, Cross, DownLeft, Empty, UpRight, UpLeft ]
    ]


track4by3 =
    [ [ Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty, Empty ]
    , [ Empty, Empty, Empty, Empty, Empty, Empty, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft ]
    , [ Empty, Empty, Empty, Empty, Empty, DownRight, Horizontal, DownLeft, Empty, UpRight, Horizontal, UpLeft ]
    , [ Empty, Empty, Empty, Empty, Empty, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, Empty ]
    , [ Empty, Empty, Empty, Empty, DownRight, Horizontal, Horizontal, DownLeft, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ Empty, Empty, Empty, Empty, DownRight, Horizontal, DownLeft, Empty, UpRight, Horizontal, UpLeft, Empty ]
    , [ Empty, Empty, Empty, Empty, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, Empty, Empty ]
    , [ Empty, Empty, Empty, Empty, DownRight, DownLeft, DownRight, DownLeft, UpRight, UpLeft, UpRight, UpLeft ]
    , [ Empty, Empty, DownRight, DownLeft, Empty, Empty, Vertical, Vertical, Empty, Empty, UpRight, UpLeft ]
    , [ Empty, Empty, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, Empty, Empty, Empty, Empty ]
    , [ Empty, Empty, DownRight, DownLeft, Empty, DownRight, UpLeft, Vertical, Empty, UpRight, Horizontal, UpLeft ]
    , [ Empty, Empty, DownRight, DownLeft, Empty, DownRight, Cross, UpLeft, Empty, UpRight, UpLeft, Empty ]
    , [ Empty, Empty, DownRight, DownLeft, DownRight, Horizontal, UpLeft, Vertical, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ Empty, Empty, DownRight, DownLeft, DownRight, Horizontal, Cross, UpLeft, UpRight, Horizontal, UpLeft, Empty ]
    , [ Empty, Empty, DownRight, DownLeft, DownRight, DownLeft, Vertical, Vertical, UpRight, UpLeft, UpRight, UpLeft ]
    , [ Empty, Empty, DownRight, DownLeft, DownRight, DownLeft, UpRight, UpLeft, UpRight, UpLeft, Empty, Empty ]
    , [ Empty, DownRight, Horizontal, DownLeft, Empty, Vertical, Empty, Vertical, Empty, UpRight, Horizontal, UpLeft ]
    , [ Empty, DownRight, Horizontal, DownLeft, Empty, Vertical, DownRight, UpLeft, Empty, UpRight, UpLeft, Empty ]
    , [ Empty, DownRight, Horizontal, DownLeft, Empty, UpRight, Horizontal, UpLeft, Empty, Empty, Empty, Empty ]
    , [ Empty, DownRight, Horizontal, DownLeft, Empty, UpRight, DownLeft, Vertical, Empty, Empty, UpRight, UpLeft ]
    , [ Empty, DownRight, Horizontal, DownLeft, DownRight, UpLeft, Empty, Vertical, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ Empty, DownRight, Horizontal, DownLeft, DownRight, UpLeft, DownRight, UpLeft, UpRight, Horizontal, UpLeft, Empty ]
    , [ Empty, DownRight, Horizontal, DownLeft, DownRight, Cross, Horizontal, UpLeft, UpRight, UpLeft, Empty, Empty ]
    , [ Empty, DownRight, Horizontal, DownLeft, DownRight, Cross, DownLeft, Vertical, UpRight, UpLeft, UpRight, UpLeft ]
    , [ Empty, DownRight, DownLeft, Empty, Empty, Vertical, Vertical, Empty, Empty, UpRight, UpLeft, Empty ]
    , [ Empty, DownRight, DownLeft, Empty, Empty, Vertical, UpRight, DownLeft, Empty, UpRight, Horizontal, UpLeft ]
    , [ Empty, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, Empty, Empty, Empty, Empty, Empty ]
    , [ Empty, DownRight, DownLeft, Empty, Empty, UpRight, Cross, DownLeft, Empty, Empty, UpRight, UpLeft ]
    , [ Empty, DownRight, DownLeft, Empty, DownRight, UpLeft, Vertical, Empty, UpRight, Horizontal, UpLeft, Empty ]
    , [ Empty, DownRight, DownLeft, Empty, DownRight, UpLeft, UpRight, DownLeft, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ Empty, DownRight, DownLeft, Empty, DownRight, Cross, UpLeft, Empty, UpRight, UpLeft, Empty, Empty ]
    , [ Empty, DownRight, DownLeft, Empty, DownRight, Cross, Cross, DownLeft, UpRight, UpLeft, UpRight, UpLeft ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, Vertical, Empty, Empty, Vertical, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, Vertical, Empty, DownRight, UpLeft, UpRight, Horizontal, UpLeft, Empty ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, Vertical, DownRight, Horizontal, UpLeft, UpRight, UpLeft, Empty, Empty ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, Vertical, DownRight, DownLeft, Vertical, UpRight, UpLeft, UpRight, UpLeft ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, UpRight, Horizontal, Horizontal, UpLeft, Empty, Empty, Empty, Empty ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, UpRight, Horizontal, DownLeft, Vertical, Empty, Empty, UpRight, UpLeft ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, UpRight, DownLeft, Empty, Vertical, Empty, UpRight, Horizontal, UpLeft ]
    , [ DownRight, Horizontal, Horizontal, DownLeft, UpRight, DownLeft, DownRight, UpLeft, Empty, UpRight, UpLeft, Empty ]
    , [ DownRight, Horizontal, DownLeft, Empty, Vertical, Empty, Vertical, Empty, UpRight, Horizontal, UpLeft, Empty ]
    , [ DownRight, Horizontal, DownLeft, Empty, Vertical, Empty, UpRight, DownLeft, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ DownRight, Horizontal, DownLeft, Empty, Vertical, DownRight, UpLeft, Empty, UpRight, UpLeft, Empty, Empty ]
    , [ DownRight, Horizontal, DownLeft, Empty, Vertical, DownRight, Cross, DownLeft, UpRight, UpLeft, UpRight, UpLeft ]
    , [ DownRight, Horizontal, DownLeft, Empty, UpRight, Horizontal, UpLeft, Empty, Empty, Empty, Empty, Empty ]
    , [ DownRight, Horizontal, DownLeft, Empty, UpRight, Horizontal, Cross, DownLeft, Empty, Empty, UpRight, UpLeft ]
    , [ DownRight, Horizontal, DownLeft, Empty, UpRight, DownLeft, Vertical, Empty, Empty, UpRight, UpLeft, Empty ]
    , [ DownRight, Horizontal, DownLeft, Empty, UpRight, DownLeft, UpRight, DownLeft, Empty, UpRight, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, Empty, Empty, Vertical, Vertical, Empty, Empty, UpRight, UpLeft, Empty, Empty ]
    , [ DownRight, DownLeft, Empty, Empty, Vertical, Vertical, DownRight, DownLeft, UpRight, UpLeft, UpRight, UpLeft ]
    , [ DownRight, DownLeft, Empty, Empty, Vertical, UpRight, Horizontal, DownLeft, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, Empty, Empty, Vertical, UpRight, DownLeft, Empty, UpRight, Horizontal, UpLeft, Empty ]
    , [ DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, Empty, Empty, Empty, Empty, Empty, Empty ]
    , [ DownRight, DownLeft, Empty, Empty, UpRight, UpLeft, DownRight, DownLeft, Empty, Empty, UpRight, UpLeft ]
    , [ DownRight, DownLeft, Empty, Empty, UpRight, Cross, Horizontal, DownLeft, Empty, UpRight, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, Empty, Empty, UpRight, Cross, DownLeft, Empty, Empty, UpRight, UpLeft, Empty ]
    , [ DownRight, DownLeft, DownRight, DownLeft, Vertical, Vertical, Vertical, Vertical, UpRight, UpLeft, UpRight, UpLeft ]
    , [ DownRight, DownLeft, DownRight, DownLeft, Vertical, Vertical, UpRight, UpLeft, UpRight, UpLeft, Empty, Empty ]
    , [ DownRight, DownLeft, DownRight, DownLeft, Vertical, UpRight, UpLeft, Vertical, UpRight, Horizontal, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, DownRight, DownLeft, Vertical, UpRight, Cross, UpLeft, UpRight, Horizontal, UpLeft, Empty ]
    , [ DownRight, DownLeft, DownRight, DownLeft, UpRight, UpLeft, Vertical, Vertical, Empty, Empty, UpRight, UpLeft ]
    , [ DownRight, DownLeft, DownRight, DownLeft, UpRight, UpLeft, UpRight, UpLeft, Empty, Empty, Empty, Empty ]
    , [ DownRight, DownLeft, DownRight, DownLeft, UpRight, Cross, UpLeft, Vertical, Empty, UpRight, Horizontal, UpLeft ]
    , [ DownRight, DownLeft, DownRight, DownLeft, UpRight, Cross, Cross, UpLeft, Empty, UpRight, UpLeft, Empty ]
    ]
